server:
  port: 8000

spring:
  application:
    name: cloud-prometheus
    
jasypt:
  encryptor:
    password: cgzz
    
aa: 
  cc: 'ENC(7wxRR36Cwd/5TM39MkRQcRax3YnOGakDgJCLNnggK6dOZPd+cFReEBETocAQMvXU)'

#日志
logging:
  config: classpath:logback-spring.xml
  level:
    java.sql.Connection: DEBUG
    java.sql.Statement: DEBUG
    java.sql.PreparedStatement: DEBUG
    org.springframework.jdbc.datasource.DataSourceTransactionManager: DEBUG
        
management:
  metrics:
    tags:
      application: ${spring.application.name}
  endpoints:
    web:
      exposure:
        include: health,info,env,prometheus,metrics,httptrace,threaddump,heapdump,springmetrics
